In [2]:
from tensorflow.keras.preprocessing.text import one_hot
import numpy as np


In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [8]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]  ##converted to vectors
one_hot_repr

[[1713, 904, 1414, 9275],
 [1713, 904, 1414, 8422],
 [1713, 8824, 1414, 6066],
 [7653, 9301, 1665, 6890, 7720],
 [7653, 9301, 1665, 6890, 628],
 [473, 1713, 7225, 1414, 8400],
 [6324, 1973, 9108, 6890]]

In [9]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1713  904 1414 9275]
 [   0    0    0    0 1713  904 1414 8422]
 [   0    0    0    0 1713 8824 1414 6066]
 [   0    0    0 7653 9301 1665 6890 7720]
 [   0    0    0 7653 9301 1665 6890  628]
 [   0    0    0  473 1713 7225 1414 8400]
 [   0    0    0    0 6324 1973 9108 6890]]


In [11]:
## feature representation
dim=10   ##10 features

In [ ]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length)) ##voc_size,dim,input_length are the parameters for embedding layer(word2vec)
model.compile('adam','mse') ##compiling the model

In [14]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.predict(embedded_docs)

2026-04-19 13:55:35.459871: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 0s 422ms/step


array([[[-0.04703686,  0.00861821, -0.01000313,  0.03822492,
         -0.04033356,  0.00628121, -0.01173867, -0.03627063,
          0.01716963, -0.03662771],
        [-0.04703686,  0.00861821, -0.01000313,  0.03822492,
         -0.04033356,  0.00628121, -0.01173867, -0.03627063,
          0.01716963, -0.03662771],
        [-0.04703686,  0.00861821, -0.01000313,  0.03822492,
         -0.04033356,  0.00628121, -0.01173867, -0.03627063,
          0.01716963, -0.03662771],
        [-0.04703686,  0.00861821, -0.01000313,  0.03822492,
         -0.04033356,  0.00628121, -0.01173867, -0.03627063,
          0.01716963, -0.03662771],
        [-0.04816961,  0.0355962 ,  0.03310032, -0.04529492,
         -0.03854885,  0.00842667, -0.02858747, -0.04602551,
          0.01785997,  0.02987733],
        [-0.02335755, -0.02602968, -0.01356093, -0.04812081,
          0.0445757 ,  0.02501453,  0.04041392, -0.01139178,
         -0.00500508, -0.01665406],
        [ 0.03183612, -0.03799081, -0.02904981, -0.0

In [16]:
embedded_docs[0] ##get first sentence embedding

array([   0,    0,    0,    0, 1713,  904, 1414, 9275], dtype=int32)

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 105ms/step


array([[-0.04703686,  0.00861821, -0.01000313,  0.03822492, -0.04033356,
         0.00628121, -0.01173867, -0.03627063,  0.01716963, -0.03662771],
       [-0.04703686,  0.00861821, -0.01000313,  0.03822492, -0.04033356,
         0.00628121, -0.01173867, -0.03627063,  0.01716963, -0.03662771],
       [-0.04703686,  0.00861821, -0.01000313,  0.03822492, -0.04033356,
         0.00628121, -0.01173867, -0.03627063,  0.01716963, -0.03662771],
       [-0.04703686,  0.00861821, -0.01000313,  0.03822492, -0.04033356,
         0.00628121, -0.01173867, -0.03627063,  0.01716963, -0.03662771],
       [-0.04816961,  0.0355962 ,  0.03310032, -0.04529492, -0.03854885,
         0.00842667, -0.02858747, -0.04602551,  0.01785997,  0.02987733],
       [-0.02335755, -0.02602968, -0.01356093, -0.04812081,  0.0445757 ,
         0.02501453,  0.04041392, -0.01139178, -0.00500508, -0.01665406],
       [ 0.03183612, -0.03799081, -0.02904981, -0.04518313, -0.04105027,
         0.04877054, -0.01326822, -0.02254273